version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.ApplicationInsights
    versions:
    - 2.16.0
  - dependency-name: pelazem.util
    versions:
    - 4.0.1
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
